server:
  port: 8081
spring:
  application:
    name: service-question
  datasource:
    url: jdbc:mysql://localhost:65501/npe
    username: npe
    password: 1145141919
  data:
    redis:
      port: 65504
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
