spring:
  datasource:
    url: jdbc:mysql://localhost:65501/npe
    username: npe
    password: 1145141919
  data:
    redis:
      port: 65504
  jackson:
    time-zone: Asia/Shanghai
    date-format: yyyy-MM-dd HH:mm:ss
    generator:
      write-numbers-as-strings: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/