server:
  port: 8082
spring:
  application:
    name: service-user
  datasource:
    url: jdbc:mysql://localhost:65501/npe
    username: npe
    password: 1145141919
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/